packages:
  - "apps/*"
  - "packages/*"
catalog:
  "@tailwindcss/vite": ^4.0.6
  "@tanstack/eslint-config": ^0.3.0
  "@tanstack/react-devtools": ^0.2.2
  "@tanstack/react-router": ^1.130.2
  "@tanstack/react-router-devtools": ^1.131.5
  "@tanstack/router-plugin": ^1.121.2
  "@testing-library/dom": ^10.4.0
  "@testing-library/react": ^16.2.0
  "@types/react": ^19.0.8
  "@types/react-dom": ^19.0.3
  "@vitejs/plugin-react": ^4.3.4
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  jsdom: ^26.0.0
  lucide-react: ^0.476.0
  prettier: ^3.5.3
  react: ^19.0.0
  react-dom: ^19.0.0
  tailwind-merge: ^3.0.2
  tailwindcss: ^4.0.6
  tw-animate-css: ^1.3.6
  typescript: ^5.7.2
  vite: ^6.3.5
  vitest: ^3.0.5
  web-vitals: ^4.2.4
catalogs:
  conflicts_@tailwindcss/vite_catalog:
    "@tailwindcss/vite": catalog
  conflicts_@tanstack/react-devtools_catalog:
    "@tanstack/react-devtools": catalog
  conflicts_@tanstack/react-router_catalog:
    "@tanstack/react-router": catalog
  conflicts_@tanstack/react-router-devtools_catalog:
    "@tanstack/react-router-devtools": catalog
  conflicts_@tanstack/router-plugin_catalog:
    "@tanstack/router-plugin": catalog
  conflicts_class-variance-authority_catalog:
    class-variance-authority: catalog
